src/layouts/Layout.astro
Adding OG description in layout
No ticket
=> Adding og description

src/components/Footer.astro, src/components/buttons/GeneralButton.astro, src/components/hero/HeroSection.astro, src/components/modals/EventsPicsModal.astro, src/components/navigation/NavButton.astro, src/components/navigation/Navbar.astro, src/components/navigation/NavbarMobileButton.astro, src/components/sections/AboutSection.astro, src/components/sections/RentSection.astro
Adding responsive structure
No ticket
=> Adding responsive structure

src/components/buttons/GeneralButton.astro, src/components/navigation/Navbar.astro
Changes in contact button
No ticket
=> Changes in contact button

src/layouts/Layout.astro
Adding smooth scroll
No ticket
=> Adding smooth scroll

src/components/carrousels/PicsCarrousel.astro
Change slider controls color
No ticket
=> Change slider controls color

README.md
Change branch in url
No ticket
=> Change branch in url

README.md
Updating readme title
No ticket
=> Updating readme title

src/components/carrousels/EventsCarrousel.astro, src/components/sections/EventsSection.astro, src/pages/eventos/index.astro
Changing events order and visual
No ticket
=> Changing events order and visual

src/components/forms/ContactForm.astro, src/components/navigation/DropDownButton.astro, src/components/sections/AboutSection.astro, src/pages/about-us/index.astro
- Fix some typos
- Add submit notification in form
No ticket
=> Fix some errors and add submit notification

package.json, src/components/Footer_nuevo.astro, src/components/carrousels/ClientsCarrousel.astro, src/components/navigation/NavButton.astro, src/components/navigation/Navbar.astro, src/components/sections/ClientsSection.astro, src/components/sections/EventsSection.astro, src/layouts/Layout.astro, src/pages/index.astro
=> Modificaciones realizadas en el carrusell de clientes, footer y menu

src/components/Footer_nuevo.astro, src/components/cards/EventCard.astro, src/components/cards/GamingCard.astro, src/components/cards/SportCard.astro, src/components/carrousels/EventsCarrousel.astro, src/components/carrousels/GamingCarrousel.astro, src/components/carrousels/SportsCarrousel.astro, src/components/forms/ContactForm.astro, src/components/navigation/NavButton.astro, src/components/navigation/Navbar.astro, src/components/sections/EventsSection.astro, src/components/sections/NewaboutSection.astro, src/pages/about-us/index.astro, src/pages/catalogo/index.astro, src/pages/contacto/index.astro, src/pages/eventos/evento/[name].astro, src/pages/eventos/index.astro
=> Cambios responsive y depuración en toda la web

src/pages/about-us/index.astro, src/pages/catalogo/index.astro, src/pages/contacto/index.astro
=> Hacemos retoques en sobre nosotros, catalogo y contacto

src/pages/about-us/index.astro, src/pages/catalogo/index.astro
=> Ajustamos un detalle en movil, en la seccion de sobre nosotros

src/components/hero/HeroSection.astro
=> Modificamos el video del inicio

src/components/Footer.astro
=> Cambiamos los enlaces del footer que llevaban a sitios incorrectos

src/components/cards/EventCard.astro, src/components/cards/SponsorCard.astro, src/components/carrousels/EventsCarrousel.astro, src/components/sections/NewaboutSection.astro, src/pages/about-us/index.astro, src/pages/catalogo/index.astro, src/pages/clientes/index.astro, src/pages/contacto/index.astro, src/pages/eventos/index.astro
=> Hacemos pequeños arreglos en el responsive

src/pages/catalogo/index.astro
=> SOlucionamos un error en catalogo

src/pages/index.astro
=> modificamos las imagenes

src/components/carrousels/EventsCarrousel.astro, src/components/carrousels/ReseñasCarrusel.astro, src/components/hero/HeroSection.astro, src/components/navigation/NavButton.astro, src/components/navigation/Navbar.astro, src/components/sections/ClientsSection.astro, src/components/sections/SponsorSection.astro, src/pages/about-us/index.astro, src/pages/catalogo/[categoria]/[text].astro, src/pages/catalogo/index.astro, src/pages/eventos/evento/[name].astro
=> Añadimos la mayoria de cambios en oxyevents que faltaban por terminar.

src/components/carrousels/EventsCarrousel.astro
=> Cambiamos distribucion y nombre a las secciones de los eventos
